
spring:
  application:
      name: storehouse
  datasource:
    #continue-on-error: false
    generate-unique-name: false
    #test-while-idle: true
    #time-between-eviction-runs-millis: 30000
    #validation-query: select 1
    # MySQL
    url: jdbc:mysql://localhost:3306/storehouse_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: default
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      connection:
        #characterEncoding: utf-8
        #CharSet: utf-8
        #useUnicode: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #show_sql: true
        #format_sql: true
        #default_schema: dbo
        #jdbc:
        #  time_zone: UTC
  # Teamleaf - use
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/  #this is the main
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  # JSP - don't use
  #mvc:
  #  view:
  #    prefix: /WEB-INF/jsp/
  #    suffix: .jsp
  # Messages
  messages:
    basename: messages
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  # FlyWay
  flyway:
    enabled: true
    locations: classpath:db.migration
logging:
  #level:
    #com.concretepage: INFO
  #file:
  #path:

