
CREATE TABLE spring_sessions (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE INDEX SPRING_SESSION_IX1 ON spring_sessions (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON spring_sessions (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON spring_sessions (PRINCIPAL_NAME);

